### ISSUE TITLE
Generating oauth2 `securitySchemes`

### ISSUE THREAD

**Issue by crashdump** [fern-api/fern-openapi#120]
Hello, 

Often, API gateways require the user to set a custom `securitySchemes` to enforce (and handle) the authentication. I could not find anything but the predefined `bearer` / `header` /  `apiKey` in [src/security.ts](https://github.com/fern-api/fern-openapi/blob/main/src/security.ts).

Example of the output I'd need to get to before I can use Fern to generate my OAS.

```
securitySchemes:
    firebase:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.foo.bar
          scopes:
            read: Grants read access
            write: Grants write access
          x-google-audiences: foo-bar
          x-google-issuer: https://securetoken.google.com/foo-bar
          x-google-jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
```

Did I miss this (and if so apologies for the noise) or is it simply not possible today?

**Comment by dsinghvi** [comment]
@crashdump a lot of folks need their OpenAPI to be custom so one thought we have is to add a custom configuration that allows you to override the generated OpenAPI. It would something like: 

```yaml
groups: 
  generators: 
    - name: "..."
       version: "..."
       config: 
         custom-overrides: # <------------ custom config that allows you to override in the generated openapi spec
           securitySchemes: 
             firebase: 
```
