### ISSUE TITLE
Objects are not nesting correctly

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-openapi#14]
`last_four` is indented to the wrong level.

```YAML
  BankConnection:
    properties:
      id:
        type: string
      bank_details:
        type: optional<BankDetails>
      brex_account_id:
        type: optional<string>
        docs: Brex cash account ID
      last_four:
        type: string
      available_balance:
        type: AvailableBalance
      current_balance:
        type: CurrentBalance

  BankDetails:
    properties:
      name:
        type: optional<string>
        docs: The name of the bank
      type:
        type: optional<BankType>

  BankType:
    enum:
      - CHECKING
      - SAVINGS
```

```JSON 
{
  "next_cursor": "string",
  "items": [
    {
      "id": "string",
      "bank_details": {
        "name": "string",
        "brex_account_id": "string",
        "last_four": "string",
        "available_balance": {
          "amount": {
            "amount": 0,
            "currency": "string"
          },
          "as_of_date": "2022-08-22T00:48:53.534Z"
        },
        "current_balance": {
          "amount": {
            "amount": 0,
            "currency": "string"
          },
          "as_of_date": "2022-08-22T00:48:53.534Z"
        }
      }
    }
  ]
}
```
