### ISSUE TITLE
Support allow-multiple in query params

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-openapi#74]
If allow_multiple is used for query params, we should represent this in the generated openapi spec.

```yaml
        - in: query
          name: myQuery
          explode: true
          schema:
            type: array
            items:
              type: string
```
